/*

389. Find the Difference
------------------------
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

*/

class Solution {
    public char findTheDifference(String s, String t) {
        int diff = 0;
        int i = 0;
        for( i = 0; i < s.length(); i++) {
            diff = diff ^ s.charAt(i) ^ t.charAt(i);
        }
        diff = diff ^ t.charAt(i);
        return (char) diff;
    }
}
